server:
  port: 8001
  tomcat:
    max-swallow-size: 100MB #tomcat的吞吐量
spring:
  servlet:
    multipart:
      max-file-size: 200KB
      max-request-size: 1MB

  kafka:
    bootstrap-servers: 192.168.1.110:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:mysql://localhost:3306/cartoon?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:
  application:
    name: com.cartoon.user
  redis:
    host: 127.0.0.1
    port: 6379

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  #使用ip注册 客户端用
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

mybatis:
  mapper-locations: classpath:mappers/*.xml

#支持的头像图片格式
headImgFormat: jpg,jpeg,png,bmp
#头像上传的路径
headImgTempPath: D:/cartoonImg

oauth:
  clientId: doctor
  clientSecret: good123

#分享链接
  #http://localhost:8001/api/user/userReg

