
probability:
  goldProbability: 19
  couponProbability: 39
  scoreProbability: 59
  ticketProbability: 79
  vipProbability: 99
giftCount:
  goldCount: 5
  couponCount: 2
  scoreCount: 100
  ticketCount: 3
  vipCount: 7
  redPacketCount: 3



server:
  port: 8003
spring:
  application:
    name: com.cartoon.panicBuying
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: 192.168.1.110:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:mysql://localhost:3306/cartoon?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  #使用ip注册 客户端用
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}


mybatis:
  mapper-locations: classpath:mappers/*.xml
