server:
  port: 8003

spring:
  application:
    name: com.gy.gift
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true


#配置hysrtix,要监控谁就给谁配，不管是用rest熔断还是feign熔断都要加下面，下面是将熔断错误的信息发送给监控者
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream #配置hystrix的流文件


#mybatis:
#  mapper-locations: classpath:mappers/*.xml

---
spring:
  profiles: dev
#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://10.100.100.105:7001/eureka/
  #使用ip注册 客户端用
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

---

spring:
  profiles: test
  datasource:
    master:
      password:
      url: jdbc:mysql://localhost:3306/master?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      type: com.zaxxer.hikari.HikariDataSource
    cluster:
      - key: slave1
        password:
        url: jdbc:mysql://localhost:3306/slave1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        idle-timeout: 20000
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        type: com.zaxxer.hikari.HikariDataSource
      - key: slave2
        password:
        url: jdbc:mysql://localhost:3306/slave2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  #使用ip注册 客户端用
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}