server:
  port: 8002

spring:
  thymeleaf:
    prefix: classpath:/templates/
  main:
    allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: 192.168.1.110:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:mysql://localhost:3306/cartoon?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:
  application:
    name: com.cartoon.social.contact
  redis:
    host: 127.0.0.1
    port: 6379
  data:
    mongodb:
      uri: mongodb://localhost:27017/col

#eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  #使用ip注册 客户端用
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

mybatis:
  mapper-locations: classpath:mappers/*.xml

page:
  size: 10
