server:
  port: 7003
spring:
  kafka:
    bootstrap-servers: 192.168.1.110:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  application:
    name: com.cartoon.user.oauth
  redis:
    host: 127.0.0.1
    port: 6379

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shop_oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password:
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka

#auth:
#  ttl: 3600  #token存储到redis的过期时间
#  clientId: doctor
#  clientSecret: good123
#  cookieDomain: localhost
#  cookieMaxAge: -1
auth:
  ttl: 10  #token存储到redis的过期时间
  clientId: doctor
  clientSecret: good123
  cookieDomain: localhost
  cookieMaxAge: -1


encrypt:
  key-store:
    location: classpath:/cartoon.jks #此为使用的密钥 需要更改密钥就更改此
    secret: aa11cartoon11aa
    alias: cartoon
    password: aa11cartoon11aa